version: "3"

services:
  mongo:
    image: mongo:3.4
    ports:
      - 27027:27017
    volumes:
      - mongo_db:/data/db

  webshop-api:
    build:
      context: ./
    ports:
      - 9999:8080
    depends_on:
      - mongo

volumes:
  mongo_db: